### ISSUE TITLE
Deand on pushed deleted ref

### ISSUE THREAD

**Issue by esnya** [ukatama/nekobuilder#1]
```
/usr/src/app/lib/task.js:47
    logger.info('Task pushed', pushData.repository.full_name, pushData.ref, pushData.head_commit.id);
                                                                                                ^

TypeError: Cannot read property 'id' of null
    at pushTask (/usr/src/app/lib/task.js:47:97)
    at IncomingMessage.<anonymous> (/usr/src/app/lib/app.js:47:40)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
```

**Comment by esnya** [comment]
Fixed on  41a93bd
